parameters:
 - group: solar
   items: 
    - name: "PV1 Power"
      uom: "W"
      scale: 1
      rule: 1
      registers: [0x00BA]
      icon: 'mdi:solar-power'

    - name: "PV2 Power"
      uom: "W"
      scale: 1
      rule: 1
      registers: [0x00BB]
      icon: 'mdi:solar-power'

    - name: "PV1 Voltage"
      uom: "V"
      scale: 0.1
      rule: 1
      registers: [0x006D]
      icon: 'mdi:solar-power'

    - name: "PV2 Voltage"
      uom: "V"
      scale: 0.1
      rule: 1
      registers: [0x006F]
      icon: 'mdi:solar-power'

    - name: "PV1 Current"
      uom: "A"
      scale: 0.1
      rule: 1
      registers: [0x006E]
      icon: 'mdi:solar-power'

    - name: "PV2 Current"
      uom: "A"
      scale: 0.1
      rule: 1
      registers: [0x0070]
      icon: 'mdi:solar-power'

    - name: "Daily Production"
      uom: "kWh"
      scale: 0.1
      rule: 1
      registers: [0x006C]
      icon: 'mdi:solar-power'

    - name: "Total Production"
      uom: "kWh"
      scale: 0.1
      rule: 3
      registers: [0x0060,0x0061]
      icon: 'mdi:solar-power'

    - name: "Micro-inverter Power"
      uom: "W"
      scale: 1
      rule: 1
      registers: [0x00A6]
      icon: 'mdi:solar-power'

 - group: Battery
   items: 
    - name: "Battery Status"
      uom: ""
      scale: 1
      rule: 1
      registers: [0x00BD]
      lookup: 
      -  key: 0
         value: "Charge"
      -  key: 1
         value: "Stand-by"
      -  key: 2
         value: "Discharge"
      icon: 'mdi:battery'

    - name: "Battery Power"
      uom: "W"
      scale: 1
      rule: 2
      registers: [0x00BE]
      icon: 'mdi:battery'

    - name: "Battery Voltage"
      uom: "V"
      scale: 0.01
      rule: 1
      registers: [0x00B7]
      icon: 'mdi:battery'

    - name: "Battery SOC"
      uom: "%"
      scale: 1
      rule: 1
      registers: [0x00B8]
      icon: 'mdi:battery'

    - name: "Battery Current"
      uom: "A"
      scale: 0.01
      rule: 2
      registers: [0x00BF]
      icon: 'mdi:battery'

    - name: "Battery Temperature"
      uom: "°C"
      scale: 0.1
      rule: 1
      registers: [0x00B6]
      icon: 'mdi:battery'

 - group: Grid
   items: 
    - name: "Grid Status"
      uom: ""
      scale: 1
      rule: 1
      registers: [0x00A9]
      lookup: 
      -  key: 0
         value: "SELL"
      -  key: 1
         value: "BUY"
      -  key: 2
         value: "Stand-by"
      icon: 'mdi:transmission-tower'

    - name: "Total Grid Power"
      uom: "W"
      scale: 1
      rule: 2
      registers: [0x00A9]
      icon: 'mdi:transmission-tower'

    - name: "Grid Voltage L1"
      uom: "V"
      scale: 0.1
      rule: 1
      registers: [0x0096]
      icon: 'mdi:transmission-tower'

    - name: "Grid Voltage L2"
      uom: "V"
      scale: 0.1
      rule: 1
      registers: [0x0097]
      icon: 'mdi:transmission-tower'

    - name: "Internal CT L1 Power"
      uom: "W"
      scale: 1
      rule: 2
      registers: [0x00A7]
      icon: 'mdi:transmission-tower'

    - name: "Internal CT L2 Power"
      uom: "W"
      scale: 1
      rule: 2
      registers: [0x00A8]
      icon: 'mdi:transmission-tower'

    - name: "External CT L1 Power"
      uom: "W"
      scale: 1
      rule: 2
      registers: [0x00AA]
      icon: 'mdi:transmission-tower'

    - name: "External CT L2 Power"
      uom: "W"
      scale: 1
      rule: 2
      registers: [0x00AB]
      icon: 'mdi:transmission-tower'

    - name: "Daily Energy Bought"
      uom: "kWh"
      scale: 0.1
      rule: 1
      registers: [0x004C]
      icon: 'mdi:transmission-tower-export'

    - name: "Total Energy Bought"
      uom: "kWh"
      scale: 0.1
      rule: 1
      registers: [0x004E,0x0050]
      icon: 'mdi:transmission-tower-export'
      
    - name: "Daily Energy Sold"
      uom: "kWh"
      scale: 0.1
      rule: 1
      registers: [0x004D]
      icon: 'mdi:transmission-tower-import'

    - name: "Total Energy Sold"
      uom: "kWh"
      scale: 0.1
      rule: 3
      registers: [0x0051,0x0052]
      icon: 'mdi:transmission-tower-import'


    - name: "Total Grid Production"
      uom: "kWh"
      scale: 0.1
      rule: 4
      registers: [0x003F,0x0040]
      icon: 'mdi:transmission-tower'

 - group: Upload
   items: 
    - name: "Total Load Power"
      uom: "W"
      scale: 1
      rule: 1
      registers: [0x00B2]
      icon: 'mdi:lightning-bolt-outline'

    - name: "Load L1 Power"
      uom: "W"
      scale: 1
      rule: 1
      registers: [0x00B0]
      icon: 'mdi:lightning-bolt-outline'

    - name: "Load L2 Power"
      uom: "W"
      scale: 1
      rule: 1
      registers: [0x00B1]
      icon: 'mdi:lightning-bolt-outline'

    - name: "Load Voltage"
      uom: "V"
      scale: 0.1
      rule: 1
      registers: [0x009D]
      icon: 'mdi:lightning-bolt-outline'

    - name: "Daily Load Consumption"
      uom: "kWh"
      scale: 0.1
      rule: 1
      registers: [0x0054]
      icon: 'mdi:lightning-bolt-outline'

    - name: "Total Load Consumption"
      uom: "kWh"
      scale: 0.1
      rule: 3
      registers: [0x0055,0x0056]
      icon: 'mdi:lightning-bolt-outline'

    - name: "SmartLoad Enable Status"
      uom: ""
      scale: 1
      rule: 1
      registers: [0x00C3]
      lookup: 
      -  key: 0
         value: "OFF"
      -  key: 1
         value: "ON"
      icon: 'mdi:lightning-bolt-outline'

 - group: Inverter
   items: 
    - name: "Running Status"
      uom: ""
      scale: 1
      rule: 1
      registers: [0x003B]
      lookup: 
      -  key: 0
         value: "Stand-by"
      -  key: 1
         value: "Self-checking"
      -  key: 2
         value: "Normal"
      -  key: 3
         value: "FAULT"
      icon: 'mdi:home-lightning-bolt'

    - name: "Total Power"
      uom: "W"
      scale: 1
      rule: 2
      registers: [0x00AF]
      icon: 'mdi:home-lightning-bolt'

    - name: "Current L1"
      uom: "A"
      scale: 0.01
      rule: 2
      registers: [0x00A4]
      icon: 'mdi:home-lightning-bolt'

    - name: "Current L2"
      uom: "A"
      scale: 0.01
      rule: 2
      registers: [0x00A5]
      icon: 'mdi:home-lightning-bolt'

    - name: "Inverter L1 Power"
      uom: "W"
      scale: 1
      rule: 2
      registers: [0x00AD]
      icon: 'mdi:home-lightning-bolt'

    - name: "Inverter L2 Power"
      uom: "W"
      scale: 1
      rule: 2
      registers: [0x00AE]
      icon: 'mdi:home-lightning-bolt'

    - name: "DC Temperature"
      uom: "°C"
      scale: 0.1
      rule: 2
      registers: [0x005A]
      icon: 'mdi:thermometer'

    - name: "AC Temperature"
      uom: "°C"
      scale: 0.1
      rule: 2
      registers: [0x005B]
      icon: 'mdi:thermometer'

    - name: "Inverter ID"
      uom: ""
      scale: 1
      rule: 5
      registers: [0x0003,0x0004,0x0005,0x0006,0x0007]
      
    - name: "Communication Board Version No."
      uom: ""
      scale: 1
      rule: 1
      registers: [0x000E]

    - name: "Control Board Version No."
      uom: ""
      scale: 1
      rule: 1
      registers: [0x000D]

    - name: "Grid-connected Status"
      uom: ""
      scale: 1
      rule: 1
      registers: [0x00C2]
      lookup: 
      -  key: 0
         value: "Off-Grid"
      -  key: 1
         value: "On-Grid"

    - name: "Gen-connected Status"
      uom: ""
      scale: 1
      rule: 1
      registers: [0x00A6]
      lookup: 
      -  key: 1
         value: "On"

    - name: "Gen Power"
      uom: "W"
      scale: 1
      rule: 1
      registers: [0x00A6]

    - name: "Time of use"
      uom: ""
      scale: 1
      rule: 1
      registers: [0x00F8]
      lookup: 
      -  key: 0
         value: "Disable"
      -  key: 1
         value: "Enable"

    - name: "Work Mode"
      uom: ""
      scale: 1
      rule: 3
      registers: [0x00F4,0x00F7]
      lookup: 
      -  key: 0
         value: "Selling First"
      -  key: 1
         value: "Zero-Export to Load&Solar Sell"
      -  key: 2
         value: "Zero-Export to Home&Solar Sell"
      -  key: 3
         value: "Zero-Export to Load"
      -  key: 4
         value: "Zero-Export to Home"
      icon: 'mdi:home-lightning-bolt'

 - group: Alert
   items: 
    - name: "Alert"
      uom: ""
      scale: 1
      rule: 6
      registers: [0x0065,0x0066,0x0067,0x0068,0x0069,0x006A]
